services:
  - type: web
    name: backend-service
    runtime: python
    buildCommand: "uv install"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    plan: free
    publish:
      directory: ./backend

  - type: web
    name: frontend-service
    runtime: python
    buildCommand: "uv install"
    startCommand: "streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
    plan: free
    publish:
      directory: ./frontend
